### ISSUE TITLE
README.md에 오타가 있다냥

### ISSUE THREAD

**Issue by nemorize** [Nyanlang/Nyanlang#3]
https://github.com/sserve-kr/Nyanlang/blob/126e9636cb99e3379e64297ec7165ce2ce834e6b/README.md?plain=1#L11

포인터 증(가)
'가' 가 빠졌다냥

**Comment by concertypin** [comment]
f5152b 커밋에서 고쳐졌다냥

**Comment by nemorize** [comment]
확인했다냥
이슈 닫겠다냥
