### ISSUE TITLE
unimplemented EOF

### ISSUE THREAD

**Issue by abiriadev** [Nyanlang/Nyanlang#4]
## 에러

Bash 기준, 다음과 같은 에러를 확인할 수 있습니다.

```bash
$ python3 interpreter.py ./eof.nyan <<< ''
Traceback (most recent call last):
  File "/home/abiria/clone/Nyanlang/interpreter.py", line 61, in <module>
    memory[pointer] = ord((lambda ip: ip[0] if len(ip) >= 1 else 0)(input()))
TypeError: ord() expected string of length 1, but int found
```

이 때, `eof.nyan`의 내용은 단순히 여러 번 입력을 받아 여러번 출력하는 내용입니다.
```bf
,,,...
```

bash가 문제가 아니라 단순히 입력을 중간에 중단하면 발생하는 이슈입니다.
(보통 `Ctrl + D`를 눌러서도 재현할 수 있습니다.)

원본 소스 중
https://github.com/sserve-kr/Nyanlang/blob/82969c5b625b51d4147f4dc424fa893f3efb0064/nyan.py#L77
다음 부분에서 내장 `input()` 함수를 사용한 것이 원인으로 보입니다.

## 제안

1. EOF 구현은 원래 정해진 기준이 없어서 brainfuck 구현체마다 다르게 구현합니다. 보통 0을 넣긴 합니다.
2. try - catch문을 통해 해당 오류를 그대로 발생시키지 않고 의도하신 구현에 맞게 처리할 수 있습니다.

만약 직접 구현하시고 싶지 않다면 PR을 보내드리겠습니다.

**Comment by p-sw** [comment]
확인했고 9ecca9bb345503375277795b6447a9a048dc685c 커밋에서 고쳤다냥.
같은 eof.nyan 파일로 다시 시도해 본 결과 `'\x00'` 문자로 에러 없이 잘 들어가는 걸 확인했다냥.
버그 제보 고맙다냥!

**Comment by abiriadev** [comment]
> 포인터가 가리키는 바이트에 ASCII 값 입력

1. 제가 해당 문장을 잘못 해석한 것인지, `ABC` 라는 입력이 있고 `,?,?,` 코드가 주어진다면 차례대로 65, 66, 67의 숫자가 저장되는 것으로 생각했 ~~다냥?~~ 습니다.
2. 해당 구현체의 코드를 다시 살펴본 결과 `A\nB\nC` 라는 입력이 주어져야 같은 동작을 하고, `ABC` 를 전달한다면 65만 입력된 채로 EOF 에러가 난다는 사실을 발견했습니다.


따라서,

1. 만약 의도하신 것이 2의 구현이 맞다면, 본 이슈는 해결된 것으로 보입니다. (다만 기존에 존재하던 brainfuck과의 호환성이 사라질 수 있습니다. 코드 호환성이 사라지는 게 아니라 입력 자체를 다르게 해석해야 하기 때문에 아마 translate만으로는 해결이 쉽지 않을 것 같습니다.)
2. 만약 의도하신 것이 1의 구현이라면 본 이슈는 해결된 것 같지 않습니다. (계속 EOF 에러가 발생합니다.) 다만 코드를 부분적으로 많이 수정해야 하기 때문에 PR #5 를 작성하였으니 검토해주신다면 감사하겠습니다.

~~그나저나 이 언어 재밌네요. 냐냐냐냐냥!~~

**Comment by abiriadev** [comment]
\+ 참고로 제가 EOF를 쓸데없이(?) 신경쓰는 거로 보일 수도 있지만 튜링 완전한 언어를 만들기 위해서는 유한 번의 시도 안에 입력이 끝나는지 알 수 있어야 합니다.

예를 들어서 말한 내용을 거꾸로 출력하는 `reverse.nyan` 코드가 있다고 해보겠습니다.

```bf
냐~? ,-! 냥~ 냐.! 냥-
```

위 코드는 아래 brainfuck 코드와 100% 같습니다.

```bf
-[>,]<+[-.<+]
```

위 brainfuck 코드가 돌아간다면 [번역 기능에 의해](https://github.com/sserve-kr/Nyanlang/wiki/%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%93%B0%EB%8A%94%EA%B1%B0%EC%A7%80%EB%83%A5%3F#%EB%B2%88%EC%97%AD%EC%9D%B4%EB%8B%A4%EB%83%A5) nyanlang 코드도 돌아가야 합니다.
하지만 현재 구현체 기준으로는 해당 코드가 작동하는 걸 볼 수가 없~~다냥~~습니다...

```bash
python3 ./nyan.py run ./reverse.nyan <<< "냥랭은 세상에서 가장 귀여운 프로그래밍 언어가 되기 위해 만들어졌다냥."

.냥다졌어들만 해위 기되 가어언 밍래그로프 운여귀 장가 서에상세 은랭냥
```

**Comment by p-sw** [comment]
믕... 내가 브레인퍽을 한번도 안다루고 문서만 보고 만든거라, 입력이 어떻게 핸들링되는지를 몰랐다냥.
PR은 merge 햇다냥.
stdin.read는 한번도 써보지를 않아서냥, 굉장히 현명한 방법이엇다냥.
좋은 지적 고맙다냥.
