### ISSUE TITLE
개발환경 추가

### ISSUE THREAD

**Issue by abiriadev** [Nyanlang/Nyanlang#6]
냥랭을 위한 [코드 포맷터](https://github.com/abiriadev/nyanfmt)를 만들었~~습니다~~다냥(?)

아직 완성되진 않았지만 [냥랭 개발환경 문서](https://github.com/sserve-kr/Nyanlang/wiki/%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD%EB%83%A5)에 다른 냥랭 언어용 도구랑 같이 추가되면 좋~~을 것 같습니다~~겠다냥(?)

다음은 현재까지 작성된 코드 포맷터의 동작 예시~~입니다~~다냥(?)

(예제다냥 문단에서 발췌)

#### 포맷 전:

```bf
냥냥냥냥냥냥냥냥~?냥냥냥냥~?냥냥?냥냥냥?냥냥냥?냥!!!!냐-?냥?냥?냐??냥~!-!냐-??.?냐냐냐.
```

#### 포맷 후:

```bf
냥냥냥냥냥 냥냥냥~? 냥냥냥냥~? 냥냥? 냥냥냥? 냥냥냥? 냥!!!! 냐-? 냥? 냥? 냐?? 냥~! -! 냐-?? .? 냐냐냐.
```

혹시 잘못 해석된 부분이 있다면 알려주시면 감사하겠~~습니다~~다냥(?)

**Comment by p-sw** [comment]
추가됐다냥!
