### ISSUE TITLE
개선점 제안

### ISSUE THREAD

**Issue by tyeongkim** [Nyanlang/Nyanlang#8]
본 언어는 Brainfuck을 모티브로 제작되었기 때문에 Interpreter 개발은 상대적으로 쉽지만 개발경험은 매우 안좋습니다.
만약 이 언어를 다른 사람이 사용할 정도의 범용성을 가지고 싶게 하고싶으시다면 더 직관적인 문법과 가독성 높은 코드가 필요합니다. 하지만 그렇게 한다면 구현 난이도가 높아지겠죠.

이 언어가 joke 목적의 프로젝트거나 컨셉을 바꾸고 싶지 않으시다면 뭐 어쩔 수 없죠

**Comment by abiriadev** [comment]
실용성과 범용성을 의도한 언어가 아니기에 구현 난이도와는 별개로 계속 현재와 비슷한 문법을 유지하게 되지 않을까 싶습니다.

**Comment by p-sw** [comment]
구현 난이도와는 별개로 문법을 바꿀 생각은 없습니다.
물론 실용성을 염두에 두고 syscall 도입 계획을 잡고는 있습니다. 물론 도입한다고 해서 범용성이 뛰어오르고 와! 냥랭 개쩐다!를 바라는 것은 아니고, 어디까지나 토이 프로젝트이므로 제가 가지고 놀 목적으로 만드는 것입니다. (웹사이트도 그의 일환이고요)
